name: Robot Framework Tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip gnupg2
          wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y libappindicator1 libindicator7
          sudo ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome
          google-chrome --version  # Debugging step

      - name: Install Browser Drivers
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          echo "CHROMEDRIVER=$(which chromedriver)" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          BASE_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
    
          # Fetch the correct ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "$BASE_URL" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
    
          # Download and set up ChromeDriver
          wget "$CHROMEDRIVER_VERSION" -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chromedriver --version  # Debugging step

      - name: Install jq (for JSON Parsing)
        run: sudo apt-get install -y jq

      - name: Debug Chrome & ChromeDriver Setup
        run: |
          which google-chrome || echo "Chrome not found!"
          google-chrome --version || echo "Google Chrome version not found!"
          which chromedriver || echo "ChromeDriver not found!"
          chromedriver --version || echo "ChromeDriver version not found!"

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
